[pytest]
markers =
    negative: marks tests as negative test cases
    smoke: marks smoke tests
    regression: marks regression tests
    login: marks login related tests
    ui: marks UI test cases
    db: mark DB test cases
    api: mark API test cases
-
--
-
-
-
-
-
-
-
-